Fix failing tests,
geobeyond/fastgeoapi pull request #7
Opened 2022-05-06 23:38 UTC by Youngestdev

1. Updated `main.py`  to include a custom FastAPI class. In this class, I have added a `logger` attribute to fix the error from `mypy`.

2. Updated the `noxfile.py` to include the `--namespace-packages` tag to ensure `mypy` pursues the library path instead of a shallow search returning a module has no attribute error.
3. Fixed the wrong class import in the `service_result.py` file.
4. Created the `mypy.ini` configuration file to ignore missing imports.

---

The mypy 3.9 test fails locally. I'm going to investigate this further if the tests fails in the action workflow.

2022-05-07 20:51 UTC, Youngestdev commented
Once [this](https://github.com/geopython/pygeoapi/pull/894) is merged, all tests will pass :D.

2022-05-09 09:55 UTC, francbartoli commented
Let's wait for the merge of https://github.com/geopython/pygeoapi/pull/894

2022-05-09 10:24 UTC, francbartoli commented
Hi @Youngestdev, as a potential alternative can we pin click>8 on our `pyproject.toml` only? Or they are conflicting and so wouldn't work?

2022-05-09 10:32 UTC, Youngestdev commented
It’s conflicting. We can instead pin to a fork/branch using the updates requirement. 

I can do that pending when the original issue is resolved.

2022-05-09 10:38 UTC, francbartoli commented
ok, we can fork `pygeoapi` eventually and keep the change on our organization in a dedicated branch called `safety`.  Let's wait for the decision from the pygeoapi side

2022-05-09 10:48 UTC, Youngestdev commented
Okay then. I’ll do that.

2022-05-09 10:56 UTC, francbartoli commented
> Okay then. I’ll do that.

you don't have the right permissions to do that right now. I'll do the fork eventually and you will send the PR for the change so that we can then use the `safety` branch in this PR

2022-05-09 11:27 UTC, francbartoli requested changes

2022-05-09 11:27 UTC, francbartoli commented on app/main.py
> +class ModifiedFastAPI(FastAPI):
@Youngestdev can you send `ModifiedFastAPI` changed into `FastGeoAPI` in the meanwhile?

2022-05-09 11:36 UTC, Youngestdev commented
Sure. Give me a few minutes. 

> On 9 May 2022, at 12:27, Francesco Bartoli ***@***.***> wrote:
> 
> ﻿
> @francbartoli requested changes on this pull request.
> 
> In app/main.py:
> 
> > @@ -17,9 +20,16 @@
>  from app.utils.request_exceptions import request_validation_exception_handler
>  
>  
> -def create_app() -> FastAPI:
> +class ModifiedFastAPI(FastAPI):
> Let's call it FastGeoAPI then
> 
> In app/main.py:
> 
> > @@ -17,9 +20,16 @@
>  from app.utils.request_exceptions import request_validation_exception_handler
>  
>  
> -def create_app() -> FastAPI:
> +class ModifiedFastAPI(FastAPI):
> @Youngestdev can you send ModifiedFastAPI changed into FastGeoAPI in the meanwhile?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-05-09 11:37 UTC, Youngestdev commented on app/main.py
> +class ModifiedFastAPI(FastAPI):
Sure.

2022-05-09 11:38 UTC, Youngestdev commented on app/main.py
> +class ModifiedFastAPI(FastAPI):
Done @francbartoli

2022-05-09 11:49 UTC, francbartoli commented
some checks are now failing again @Youngestdev

2022-05-09 12:13 UTC, Youngestdev commented
I'll take a look at them.

2022-05-15 20:48 UTC, francbartoli approved these changes

2022-05-15 20:49 UTC, merged